stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  data_pre:
    cmd: python src/data_prep.py
    deps:
    - data/raw/data.csv
    - src/data_prep.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  model_buid:
    cmd: python src/model_build.py
    deps:
    - data/processed
    - src/model_build.py
    outs:
    - models/model.pkl
  model_eval:
    cmd: python src/model_eval.py
    deps:
    - data/processed
    - models/model.pkl
    - src/model_eval.py
    outs:
    - metrics/metrics.csv
